#!/bin/bash

IFS=',' read -r -a layouts <<< `setxkbmap -query | grep layout |awk '{print $NF}'`
kbl=`xset -q|grep -A 0 'LED'|cut -c59-67`

if [[ $kbl -eq "00000002" ]]; then
	setxkbmap ${layouts[1]},${layouts[0]}
	else
	setxkbmap ${layouts[0]},${layouts[1]}
fi
